version: '3.7'
services:
    flask:
        env_file:
            - ./.env
        ports:
            - 8000:8000
    environment:
        - FLASK_APP=quickslack:APP
    redis:
        ports:
            - 6379:6379
    postgres:
        env_file:
            - ./.env
        ports:
            - 5432:5432
    task-monitor:
        env_file:
            - ./.env
        ports:
            - 5555:5555
    api:
        ports:
            - 8080:8080
    notebook_server:
        build: ./notebook_server
        volumes:
            - './notebook_server/notebooks:/notebooks'
        command: jupyter lab
        ports:
            - 8888:8888