version: '3.7'
services:

    flask:
        build: ./flask
        command: bash -c 'sleep 1 && flask db upgrade && gunicorn -c "python:config.gunicorn" --reload "quickslack.app:create_app()"'
        container_name: flask
        restart: unless-stopped
        volumes:
            - './flask:/flask'

    redis:
        image: redis:3.0-alpine
        command: redis-server --requirepass devpassword
        restart: unless-stopped
        volumes:
            - 'redis:/var/lib/redis/data'
            
    celery:
        build: ./flask
        command: celery worker -l info -A quickslack.CELERY
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - './flask:/flask'

    task-monitor:
        build: ./flask
        entrypoint: flower
        command: -A quickslack.CELERY
        restart: unless-stopped
        volumes:
            - './flask:/flask'

    postgres:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres:/var/lib/postgresql/data

    api:
        container_name: model
        restart: unless-stopped
        build: './model'
        command: gunicorn -c "python:config.gunicorn" --reload "api.app:create_app()" --timeout 120 
        #command: flask run --host 0.0.0.0
        environment: 
            FLASK_RUN_PORT: 8080
            FLASK_APP: "api:APP"
        volumes:
            - './model:/api'

volumes:
    postgres:
    redis: