version: '3.7'
services:
    flask:
        env_file:
            - ./.env
        volumes:
            - './flask:/flask'
        ports:
            - 8000:8000
    redis:
        ports:
            - 6379:6379
        volumes:
            - 'redis:/var/lib/redis/data'
    celery:
        env_file:
            - ./.env
        volumes:
            - './flask:/flask'
    postgres:
        env_file:
            - ./.env
        ports:
            - 5432:5432
    task-monitor:
        env_file:
            - ./.env
        ports:
            - 5555:5555
        volumes:
            - './flask:/flask'
    model:
        ports:
            - 8080:8080
        volumes:
            - './model:/api'
        environment: 
            FLASK_RUN_PORT: 8080
            FLASK_APP: "api:APP"
    notebook_server:
        build: ./notebook_server
        volumes:
            - './notebook_server/notebooks:/notebooks'
        command: jupyter lab
        ports:
            - 8888:8888
    rasa:
        volumes:
        - './rasa_api:/rasa_api'
        ports:
        - 5005:5005
volumes:
    postgres:
    redis: