version: '3.7'
services:
  flask:
    image: quickslack/webapp:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:webapp.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=8000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    ports:
      - 8080:8080
  api:
    image: quickslack/modelapi:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:webapp.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    ports:
      - 8080:8080
  task-monitor:
      image: quickslack/webapp:${BUILD_TAG}
      networks:
        - net
  redis:
    networks: 
      - net
  postgres:
    networks: 
      - net
networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
    
