version: '3.7'
services:
  celery:
    image: quickslack/webapp:${BUILD_TAG}
  rasa:
    image: quicslack/rasa_api:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:rasa_app.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=5005
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}

  flask:
    image: quickslack/webapp:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:webapp.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=8000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    ports:
      - published: 8000
    environment: 
      FLASK_APP: "quickslack:APP"
      SLACK_EMAIL: ${SLACK_EMAIL}
      SLACK_PASSWORD: ${SLACK_PASSWORD}
      SLACK_WORKSPACE: ${SLACK_WORKSPACE_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_SERVICE: ${DB_SERVICE}
  api:
    image: quickslack/modelapi:${BUILD_TAG}
    networks:
      - net
    ports:
      - 8080:8080
  task-monitor:
      image: quickslack/webapp:${BUILD_TAG}
      labels:
        - traefik.frontend.rule=Host:flower.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=5555
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
      ports: 
        - published: 5555

      networks:
        - net
        - traefik-public
  redis:
    networks: 
      - net
  postgres:
    networks: 
      - net
networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
    
