version: '3.7'
services:
  celery:
    image: quickslack/webapp:${BUILD_TAG}
    environment:
      SLACK_EMAIL: ${SLACK_EMAIL}
      SLACK_PASSWORD: ${SLACK_PASSWORD}
      SLACK_WORKSPACE_URL: ${SLACK_WORKSPACE_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_SERVICE: ${DB_SERVICE}
      SECRET_KEY: ${SECRET_KEY}
  rasa:
    image: quickslack/rasa_api:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:rasabot.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=5005
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}

  rasa1:
    image: quickslack/rasa_api:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:rasabot1.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=5005
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN1}

  flask:
    image: quickslack/webapp:${BUILD_TAG}
    deploy:
      labels:
        - traefik.frontend.rule=Host:webapp.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=8000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - net
      - traefik-public
    environment:
      FLASK_APP: "quickslack:APP"
      SLACK_EMAIL: ${SLACK_EMAIL}
      SLACK_PASSWORD: ${SLACK_PASSWORD}
      SLACK_WORKSPACE_URL: ${SLACK_WORKSPACE_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_SERVICE: ${DB_SERVICE}
      SECRET_KEY: ${SECRET_KEY}
  model:
    image: quickslack/modelapi:${BUILD_TAG}
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.labels.gpu == cuda
  model1:
    image: quickslack/modelapi:${BUILD_TAG}
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.labels.gpu == cuda
  
  task-monitor:
      image: quickslack/webapp:${BUILD_TAG}
      labels:
        - traefik.frontend.rule=Host:flower.${BUILD_TAG}.qs.somethingtechie.com
        - traefik.enable=true
        - traefik.port=5555
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
      environment:
        SLACK_PASSWORD: ${SLACK_PASSWORD}
        SLACK_WORKSPACE_URL: ${SLACK_WORKSPACE_URL}
        SLACK_TOKEN: ${SLACK_TOKEN}
        DB_NAME: ${DB_NAME}
        DB_PASS: ${DB_PASS}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_SERVICE: ${DB_SERVICE}
        SECRET_KEY: ${SECRET_KEY}
      networks:
        - net
        - traefik-public
  redis:
    networks: 
      - net
  postgres:
    environment: 
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.labels.gpu == cuda
networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
    
