version: '3.7'
services:

    flask:
        build: ./flask
        command: bash -c 'sleep 1 && flask db upgrade && gunicorn -c "python:config.gunicorn" --reload "quickslack.app:create_app()"'
        container_name: flask
        restart: unless-stopped
        environment:
            FLASK_RUN_PORT: 8000
            FLASK_APP: "quickslack:APP"
            FLASK_ENV: development

    redis:
        image: redis:3.0-alpine
        command: redis-server --requirepass devpassword
        restart: unless-stopped
            
    celery:
        build: ./flask
        command: celery worker -l info -A quickslack.CELERY
        restart: unless-stopped
    task-monitor:
        build: ./flask
        entrypoint: flower
        command: -A quickslack.CELERY
        restart: unless-stopped

    postgres:
        image: postgres:latest
        restart: unless-stopped

    api:
        container_name: model
        restart: unless-stopped
        build: './model'
        command: gunicorn -c "python:config.gunicorn" --reload "api.app:create_app()" --timeout 120 
        

volumes:
    postgres:
    redis:
