"""empty message

Revision ID: 57f3951597c0
Revises: 
Create Date: 2020-01-23 23:11:22.197394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f3951597c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('password', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('channel',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=10), nullable=True),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('message',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.channel_id'], ),
    sa.PrimaryKeyConstraint('db_id')
    )
    op.create_table('reply',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('ts', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('thread_ts', sa.Float(), nullable=True),
    sa.Column('channel_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.channel_id'], ),
    sa.PrimaryKeyConstraint('db_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('message')
    op.drop_table('channel')
    op.drop_table('admins')
    # ### end Alembic commands ###
